### ISSUE TITLE
'The selected file is not a valid solution file' when opening StarBreaker.slnx

### ISSUE THREAD

**Issue by m4yc3x** [diogotr7/StarBreaker#1]
Before and after providing the folder and subfolders with the appropriate permissions, the solution (.slnx) file will not open in Visual Studio 2022. It closes the project with 

> The selected file is not a valid solution file
and
> Error HRESULT E_FAIL has been returned from a call to a COM component.

Opening the individual .csproj files works but I cannot build them because they rely on parent libraries such as StarBreaker.common. Any ideas on how to fix this? I believe it might have to do with the parent folder name not matching in the solution file, but correcting the folder name does not yield a success.

```
<Folder Name="/Solution Items/">
    <File Path="Directory.Build.props" />
    <File Path="..\README.md" />
    <File Path="..\.gitignore" />
    <File Path="..\crc32c.html" />
    <File Path="..\scripts\mitm.ps1" />
    <File Path="..\scripts\stream-sc.py" />
  </Folder>
  ```

I'm looking forward to contributing!

**Comment by diogotr7** [comment]
Hey, please make sure you have VS up to date. This new format was added pretty recently. If it still won't work I can always add back the old one alongside.

**Comment by m4yc3x** [comment]
> Hey, please make sure you have VS up to date. This new format was added pretty recently. If it still won't work I can always add back the old one alongside.

I thought this might be the case so I updated to the latest version (not the Preview Release). I have tried some other things such as editing VS settings but I cannot get the SLNX to open correctly, if there is a way to add a SLN file to the repo, that'd be amazing!

**Comment by diogotr7** [comment]
Strange, I use Rider which supports the new format well. I've added the old one back. I'm not sure if it's working 100% but I'm not doinjg anything out of the ordinary with it so I expect it will work correctly.
